parameters:
  depth:
    min: 4
    max: 12
    step: 1
    start: 8
  learning_rate:
    min: 0.02
    max: 0.6
    step: 0.02
    start: 0.06
  l2_leaf_reg:
    min: 1.0
    max: 30.0
    step: 1.0
    start: 3.0
  subsample:
    min: 0.5
    max: 1.0
    step: 0.05
    start: 0.8
  random_strength:
    min: 0.0
    max: 5.0
    step: 0.2
    start: 1.0
  bagging_temperature:
    min: 0.0
    max: 10.0
    step: 0.5
    start: 1.0
