parameters:
  history_length:
    min: 32
    max: 128
    step: 32
  units:
    min: 128
    max: 1024
    step: 128
  num_layers:
    values: [4, 8, 16, 32]
  dropout:
    min: 0.2
    max: 0.5
    step: 0.05
  batch_size:
    min: 128
    max: 256
    step: 32
  learning_rate:
    min: 0.0004
    max: 0.0012
    step: 0.0002
  weight_decay:
    min: 0.0
    max: 0.01
    step: 0.002
