parameters:
  history_length:
    min: 32
    max: 192
    step: 16
    start: 80
  units:
    min: 128
    max: 1024
    step: 32
    start: 224
  num_layers:
    values: [4, 8, 12, 16, 24, 32, 64]
    start: 8
  dropout:
    min: 0.2
    max: 0.5
    step: 0.05
    start: 0.3
  batch_size:
    min: 128
    max: 384
    step: 16
    start: 192
  learning_rate:
    min: 0.0004
    max: 0.0020
    step: 0.0002
    start: 0.0006
  weight_decay:
    min: 0.0
    max: 0.01
    step: 0.002
    start: 0.0
