parameters:
  mid_layer_count:
    min: 2
    max: 16
    step: 2
    start: 4
  mid_layer_size:
    min: 256
    max: 1024
    step: 32
    start: 512
  history_length:
    min: 16
    max: 128
    step: 8
    start: 80
  dropout:
    min: 0.1
    max: 0.5
    step: 0.05
    start: 0.3
  batch_size:
    min: 128
    max: 512
    step: 16
    start: 256
  learning_rate:
    min: 0.0004
    max: 0.002
    step: 0.0002
    start: 0.0008
  weight_decay:
    min: 0.0
    max: 0.01
    step: 0.002
    start: 0.0
