parameters:
  history_length:
    min: 16
    max: 128
    step: 8
    log: false
  mid_layer_count:
    min: 2
    max: 16
    step: 2
    log: false
  mid_layer_size:
    min: 128
    max: 1024
    step: 32
    log: false
  dropout:
    min: 0.1
    max: 0.5
    log: true
  batch_size:
    min: 128
    max: 512
    step: 16
    log: false
  learning_rate:
    min: 0.0004
    max: 0.002
    log: true
  weight_decay:
    min: 0.0
    max: 0.01
    log: true