model:
  type: MLP
  name: mlp_regressor/tmp_batch_size_2c4d92
  history_length: 1
  hidden_layers:
  - 1088
  - 544
  - 544
  - 544
  - 544
  - 272
  dropout: 0.3
training:
  max_epochs: 400
  batch_size: 224
  learning_rate: 0.0008
  weight_decay: 0.002
  checkpoint_interval: 10
  seed: 42
data:
  input_csv: data/time_aligned_data.csv
  timestamp_column: Date, Time
